server:
  port: 8082

spring:
  application:
    name: ride-service


  datasource:
    url: jdbc:mysql://localhost:3306/uberdb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:

      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  kafka:
    bootstrap-servers: localhost:9092


    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: ride-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ride_service.dto.DriverFoundEvent


location-service:
  url: http://localhost:8081

logging:
  level:
    com.ride_service: DEBUG
